### ISSUE TITLE
Paddle does not throw any exception when the Canoe step does not exists

### ISSUE THREAD

**Issue by federicoreppucci-deliveroo** [deliveroo/paddle#50]
When a canoe step does not exist in the yaml canoe file, Paddle doesn't throw any exception.

Example:
- Jenkins file: [Jenkinsfile-ALG-255-bug](https://github.com/deliveroo/ad-platform-algos/blob/bugfix/ALG-255-canoe-step-not-found/src/ad_platform_algos/tutorial/jenkins/Jenkinsfile-ALG-255-bug)
- Canoe file: [canoe-ALG-255-bug.yml](https://github.com/deliveroo/ad-platform-algos/blob/bugfix/ALG-255-canoe-step-not-found/src/ad_platform_algos/tutorial/canoe/canoe-ALG-255-bug.yml)
- Jenkins run: [link](https://jenkins-canoe-staging.deliveroo-data-test.io/blue/organizations/jenkins/ad-platform-algos-ALG-255-bug/detail/bugfix%2FALG-255-canoe-step-not-found/1/pipeline/)

In the `canoe-ALG-255-bug.yml` file there is only one step defined, called `step_name `. In the `Jenkinsfile-ALG-255-bug` file there are 2 stages: the former runs the canoe step `step_name `, the latter runs the canoe step `step_different_name` - that does not exist.

Jenkins does not fail when it tries to run the step `step_different_name`, and probably the reason is that Paddle does not throw an exception when the canoe step does not exist in the yaml canoe file.

**Comment by me** [comment]
Closing as the repo is being archived
